sonar.organization=solutionsone
sonar.projectKey=com.food.ordering.system:com.food.ordering.system
sonar.projectName='system-food-ordering'
sonar.projectVersion=latest
sonar.links.homepage=https://sonarcloud.io/organizations/solutionsone/projects
sonar.links.scm=https://sonarcloud.io/project/configuration?id=solutionsone_system-food-ordering